#!/usr/bin/env python
import numpy as np
import math
from seppyio import *

thickness=get_array('thickness')
vz=get_array('vz')
eps=get_array('eps')
delta=get_array('delta')

n=len(thickness)
print 'number of layers: ',n

t0=thickness[0]/vz[0]
t=t0
vnmo=vz[0]*math.sqrt(1+2*delta[0])
vnmo2t0=vnmo*vnmo*t0
vrms=math.sqrt(vnmo2t0/t)
eta=(eps[0]-delta[0])/(1+2*delta[0])
a=vnmo*vnmo*vnmo*vnmo*(1+8*eta)
at0=a*t0
etarms=(at0/t/vrms/vrms/vrms/vrms-1)/8
print 'RMS values layer 1: t0=%f Vnmo=%f Eta=%f\n' % (t0,vrms,etarms)

for i in range(1,n):
    t0=thickness[i]/vz[i]
    t=t+t0
    vnmo=vz[i]*math.sqrt(1+2*delta[i])
    vnmo2t0=vnmo2t0+vnmo*vnmo*t0
    vrms=math.sqrt(vnmo2t0/t)
    eta=(eps[i]-delta[i])/(1+2*delta[i])
    a=vnmo*vnmo*vnmo*vnmo*(1+8*eta)
    at0=at0+a*t0
    etarms=(at0/t/vrms/vrms/vrms/vrms-1)/8
    print 'RMS values layer %i: t0=%f Vnmo=%f Eta=%f\n' % (i+1,t,vrms,etarms)

