#!/usr/bin/env python

import numpy as np
from seppyio import *
import matplotlib
import matplotlib.pyplot as plt

matplotlib.rcParams.update({'font.size':15})

nz,oz,dz=from_header("hfile","n1","o1","d1")
nx,ox,dx=from_header("hfile","n2","o2","d2")
ny,oy,dy=from_header("hfile","n3","o3","d3")
na,oa,da=from_header("hfile","n4","o4","d4")

a=read("hfile",(na,ny,nx,nz))
xloc=get_array('xloc')
n=len(xloc)
yloc=get_array('yloc')

figwidth=get_param("figwidth")
if figwidth==False:
    figwidth=2.5
figheight=get_param("figheight")
if figheight==False:
    figheight=10.

temp=searchArgv('maxval')
if temp==False: 
    maxval=np.max(a) 
else:
    maxval=float(temp)

temp=searchArgv('minval')
if temp==False: 
    minval=np.min(a) 
else:
    minval=float(temp)


f,ax=plt.subplots(1,n,sharey=True,figsize=(figwidth*n,figheight))
plt.subplots_adjust(wspace=0,hspace=0)

xlabel=searchArgv('xlabel')
f.text(0.5,0.06,xlabel,ha='center')
ylabel=searchArgv('ylabel')
ax[0].set_ylabel(ylabel)

for i in range(n):
    ix=int((xloc[i]-ox)/dx)
    iy=int((yloc[i]-oy)/dy)
    if ix<nx:
        ax[i].imshow(np.transpose(a[:,iy,ix,:]),interpolation='none',aspect='auto',extent=[oa*1e-3,(oa+(na-1)*da)*1e-3,(oz+(nz-1)*dz)*1e-3,oz*1e-3],vmin=minval,vmax=maxval,cmap='gray')
        ax[i].set_ylim(0,oz+(nz-1)*dz*1e-3)
        ax[i].invert_yaxis()

xloc=np.asarray(xloc)
yloc=np.asarray(yloc)
xloc=(xloc-650000)*1e-3
yloc=(yloc+20000)*1e-3
titles=get_sarray('title')
if titles==False:
    titles=[]
    for i in range(n):
        titles.append('x='+str(round(xloc[i],2))+' km\ny='+str(round(yloc[i],2))+' km')
        ax[i].set_title(titles[i])

temp=searchArgv('out')
if temp==False: 
    plt.show()
else:
    plt.savefig(temp,bbox_inches='tight')

