#!/usr/bin/env python

import numpy as np
from seppyio import *
from subprocess import call

filename=searchArgv('hfile') 
binfile=searchFile(filename,'in')
binfile=binfile.rstrip('\n')
binfile=binfile.strip('"')

call(["rm","-f",filename])
call(["rm","-f",binfile])

