#!/usr/bin/env tcsh

./Bin/fwi-newton-param.x par=./Par/par.fault.p parameter=vepsdel wavelet=ricker.5hz.fault.H souloc=souloc.uniform.fault.H recloc=recloc.uniform.fault.H data=data.5hz.uniform.fault.H wbottom=200. padded=0 v=/homes/sep/huyle/FaultModel/bgVpz.Fault.H eps=/homes/sep/huyle/FaultModel/bgEps.Fault.H del=/homes/sep/huyle/FaultModel/bgDel.Fault.H iv=v.newton2.5hz.uniform.fault.vepsdel.H ieps=eps.newton2.5hz.uniform.fault.vepsdel.H idel=del.newton2.5hz.uniform.fault.vepsdel.H gv=gv.newton2.5hz.uniform.fault.vepsdel.H geps=geps.newton2.5hz.uniform.fault.vepsdel.H gdel=gdel.newton2.5hz.uniform.fault.vepsdel.H objfunc=objfunc.newton2.5hz.uniform.fault.vepsdel.H check=check.newton2.5hz.uniform.fault.vepsdel.H nfg=2000 v0=2963.05 eps0=0.706 del0=1 niter_max=100 >& fwi.newton2.5hz.uniform.fault.vepsdel.log

./Bin/fwi-newtonGN-param.x par=./Par/par.fault.p parameter=vepsdel wavelet=ricker.5hz.fault.H souloc=souloc.uniform.fault.H recloc=recloc.uniform.fault.H data=data.5hz.uniform.fault.H wbottom=200. padded=0 v=/homes/sep/huyle/FaultModel/bgVpz.Fault.H eps=/homes/sep/huyle/FaultModel/bgEps.Fault.H del=/homes/sep/huyle/FaultModel/bgDel.Fault.H iv=v.newtonGN.5hz.uniform.fault.vepsdel.H ieps=eps.newtonGN.5hz.uniform.fault.vepsdel.H idel=del.newtonGN.5hz.uniform.fault.vepsdel.H gv=gv.newtonGN.5hz.uniform.fault.vepsdel.H geps=geps.newtonGN.5hz.uniform.fault.vepsdel.H gdel=gdel.newtonGN.5hz.uniform.fault.vepsdel.H objfunc=objfunc.newtonGN.5hz.uniform.fault.vepsdel.H check=check.newtonGN.5hz.uniform.fault.vepsdel.H nfg=200 v0=2963.05 eps0=0.706 del0=1 niter_max=5 >& fwi.newtonGN.5hz.uniform.fault.vepsdel.log

./Bin/fwi-lbfgs-c-param.x par=./Par/par.fault.p parameter=vepsdel wavelet=ricker.5hz.fault.H souloc=souloc.uniform.fault.H recloc=recloc.uniform.fault.H data=data.5hz.uniform.fault.H wbottom=200. padded=0 v=/homes/sep/huyle/FaultModel/bgVpz.Fault.H eps=/homes/sep/huyle/FaultModel/bgEps.Fault.H del=/homes/sep/huyle/FaultModel/bgDel.Fault.H iv=v.lbfgsc1.5hz.uniform.fault.vepsdel.H ieps=eps.lbfgsc1.5hz.uniform.fault.vepsdel.H idel=del.lbfgsc1.5hz.uniform.fault.vepsdel.H gv=gv.lbfgsc1.5hz.uniform.fault.vepsdel.H geps=geps.lbfgsc1.5hz.uniform.fault.vepsdel.H gdel=gdel.lbfgsc1.5hz.uniform.fault.vepsdel.H objfunc=objfunc.lbfgsc1.5hz.uniform.fault.vepsdel.H check=check.lbfgsc1.5hz.uniform.fault.vepsdel.H nfg=100 v0=2963.05 eps0=0.706 del0=1 >& fwi.lbfgsc1.5hz.uniform.fault.vepsdel.log

./Bin/hessianMatrix.x par=./Par/par0.p parameter=vhepsdel wavelet=ricker.10Hz.0.H souloc=souloc.uniform.0.H recloc=recloc.uniform.0.H data=data.uniform.0.H wbottom=0. padded=0 vh=bgv0.H eps=zero0.H del=zero0.H hessmat=hessmat.uniform.0.full.vhepsdel.correctadj.H vh0=2000 eps0=1 del0=1 hesstype=full >& hessmat.vhepsdel.full.log

./Bin/hessianMatrix.x par=./Par/par0.p parameter=vepsdel wavelet=ricker.10Hz.0.H souloc=souloc.uniform.0.H recloc=recloc.uniform.0.H data=data.uniform.0.H wbottom=0. padded=0 v=bgv0.H eps=zero0.H del=zero0.H hessmat=hessmat.uniform.0.GN.vepsdel.H v0=2000 eps0=1 del0=1 hesstype=GN >& hessmat.vepsdel.GN.log

./Bin/hessian.x par=./Par/par1.p parameter=vepsdel wavelet=ricker.10Hz.0.H souloc=souloc.uniform.0.H recloc=recloc.uniform.0.H data=data.uniform.0.H wbottom=0. padded=0 v=bgv0.H eps=zero0.H del=zero0.H dv=dv0.H deps=zero0.H ddel=zero0.H gv=hv.uniform.0.full.vepsdel.correctadj.H geps=heps.uniform.0.full.vepsdel.correctadj.H gdel=hdel.uniform.0.full.vepsdel.correctadj.H v0=1 eps0=1 del0=1 hesstype=full 

./Bin/rtm-param.x parameter=vvnvh par=./Par/par.fault20.p wavelet=ricker.20hz.fault.H souloc=souloc.alloff.fault.H recloc=recloc.alloff.fault.H data=data.20hz.alloff.fault.H wbottom=200. v=v.lbfgsc.5hz.alloff.fault.cij.rescale.final.H vn=vn.lbfgsc.5hz.alloff.fault.cij.rescale.final.H vh=vh.lbfgsc.5hz.alloff.fault.cij.rescale.final.H image=image.20hz.alloff.fault.cij.H 

./Bin/odcig-param.x parameter=vvnvh par=./Par/par.fault20.p wavelet=ricker.20hz.fault.H souloc=souloc.alloff.fault.H recloc=recloc.alloff.fault.H data=data.20hz.alloff.fault.H wbottom=200. v=v.lbfgsc.5hz.alloff.fault.cij.rescale.final.H vn=vn.lbfgsc.5hz.alloff.fault.cij.rescale.final.H vh=vh.lbfgsc.5hz.alloff.fault.cij.rescale.final.H max_subhx=500. image=odcig.20hz.alloff.fault.cij.H 



